---
- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  when: reboot_required_file.stat.exists
  ansible.builtin.reboot:
  become: yes
